### PR TITLE
Added Wack Club Sans

### PR DESCRIPTION
**Pull request by Aquoria**
Added WOFF and WOFF2 of Wack Club Sans font to ./fonts/Wack_Club_Sans

Put .zip compressed version in ./fonts

### CODE REVIEW

**Review by aramshiva — APPROVED** [review]

**Comment by aramshiva** [comment]
@Aquoria Would you want to add this to the hack club site's asset page aswell? There is an issue open and it would be amazing aswell!

**Comment by Aquoria** [comment]
Yes, my intention is, just like the other fonts, upload this here, then pull from here to use it in the (at)hackclub/theme npm package https://hackclub.com/theme, and then pull from that to put it on the site brand page

**Review by sampoder — COMMENTED** [review]
Can you delete the `.DS_Store`?

**Comment by Aquoria** [comment]
ffs.. im so sorry I though I did

**Comment by Aquoria** [comment]
@sampoder deleted it.. sorry again I thought I had, I guess I deleted 2 of the 3

**Comment by sampoder** [comment]
let's do it

**Pull request merged**
